name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: yarn install
        run: |
          yarn cache clean
          yarn install --network-concurrency 1
      - run: yarn lint
      - run: yarn type:check
      - run: yarn format:check
      - run: yarn test
